dist: trusty
# language: minimal - Montana Mendy 
language: java
jdk:
  - oraclejdk8 # (theoretically use Abiarm API for speed?) - Montana Mendy 

cache:
  directories:
  - $HOME/.m2

install:
  - travis_wait mvn -q -Pdev,dist install -DskipTests

script:
  - uname -a
  - free
  - mvn -Dsurefire.forkCount=4 -Pdev verify
